# Generated by Django 3.2.19 on 2024-08-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
